spring:
  application:
    name: entreprise-service
  datasource:
    url: jdbc:postgresql://postgres-dev:5432/entreprise
    username: nassim
    password: colonel
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
management:
  endpoints.web.exposure.include: health,info,prometheus
