spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: demo-service
          uri: http://demo-service:8085
          predicates:
            - Path=/api/demo/**
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
