spring:
  cloud:
    gateway:
      default-filters:
        - SaveSession
      routes:
        - id: user
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: comptabilite
          uri: http://comptabilite-service:8083
          predicates:
            - Path=/api/compta/**
          filters:
            - StripPrefix=1
        - id: demo-service
          uri: http://demo-service:8085
          predicates:
            - Path=/api/demo/**
        - id: entreprise-service
          uri: http://entreprise-service-dev.startentreprise-dev.svc.cluster.local
          predicates:
            - Path=/api/enterprises/**
      # CORS itbadlo mn be3d 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
management:
  endpoint:
    gateway:
      enabled: true
